### ISSUE TITLE
Simplify tracking method of all elements

### ISSUE THREAD

**Issue by AngelFP** [AngelFP/Wake-T#4]
The method to track a particle bunch through an element currently takes several arguments. This is particularly true for the plasma stages, where a large number of optional arguments have been added over time to adapt to different tracking modes.

Many of these options could be moved to the initial definition of the elements, such that the tracking method does not take any argument except for the bunch. 

Tasks to perform for plasma elements:
- [x] Have a single tracking method and not one for the numerical solver and another for the analytical. Simply add an option `tracking_mode` to the `PlasmaStage.__init__` which can take the `'analytical'` or `'numerical'` values.
- [x] Change the name of current option `mode` for `wakefield_model`, which takes a string with the name of the wakefield model to use. Move this option to `PlasmaStage.__init__`.

In general:
- [x] The tracking method of all elements must have the same name and arguments.
- [x] After this, a general `track` method could be defined which takes as input a `bunch` and a `beamline` (a list with beamline elements) which calls the tracking method of each element and returns the new bunch distribution.
